language: python
python: '3.6'

addons:
  apt:
    packages:
    - python-pip

install:
- pip install ansible

before_script:
- wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
- unzip packer_1.3.3_linux_amd64.zip

script:
- cd repo && ../packer build aws-ami.json