language: python
python: '3.6'

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

before_script:
  - sudo rm /usr/bin/python3 && sudo ln -s ~/virtualenv/python3.6/bin/python3.6 /usr/bin/python3
  - wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
  - unzip packer_1.3.3_linux_amd64.zip

env:
  - IMAGE_ID=docker
  - IMAGE_ID=jenkins
  - IMAGE_ID=monitor
  - IMAGE_ID=repo

script:
  - cd $IMAGE_ID && ../packer build aws-ami.json
