# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/bionic64"
    docker.vm.network "private_network", ip: "192.168.33.10"
    docker.ssh.insert_key = false
    docker.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--uartmode1', 'disconnected']
    end
    docker.vm.provision "ansible" do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "playbook-docker.yml"
      ansible.host_vars = {
        "docker" => {"ansible_python_interpreter" => "/usr/bin/python3"}
      }
    end
  end
end
