---
- hosts: jenkins
  become: yes
  gather_facts: no
  roles:
  - codeyourinfra.oracle_java8
  tasks:
  - name: Install apt-transport-https (required for the apt_repository task)
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: Install latest Jenkins
    import_tasks: jenkins-installation.yml
    tags:
      - jenkins-installation
