---
- hosts: jenkins
  become: yes
  gather_facts: no
  roles:
  - codeyourinfra.jenkins
  tasks:
  - name: Get Java version
    shell: java -version
    register: java_version_result
  - name: Show Java version
    debug:
      msg: "{{ java_version_result.stderr_lines[0] | regex_search('([\\d.]+_\\d*)') }}"
  - name: Get Jenkins version
    shell: java -jar /usr/share/jenkins/jenkins.war --version
    register: jenkins_version_result
  - name: Show Jenkins version
    debug:
      msg: "{{ jenkins_version_result.stdout_lines[0] | regex_search('([\\d.]+)') }}"
