# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/xenial64"
    jenkins.vm.network "private_network", ip: "192.168.33.10"
    jenkins.ssh.insert_key = false
    jenkins.vm.provision "ansible" do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "playbook-jenkins.yml"
      ansible.host_vars = {
        "jenkins" => {"ansible_python_interpreter" => "/usr/bin/python3"}
      }
    end
  end
end
