---
- hosts: monitor
  become: yes
  tasks:
  - name: Install required Ubuntu packages
    apt:
      name: '{{item}}'
      update_cache: yes
    loop:
      - apt-transport-https
      - python3-pip
    tags:
      - installation
  - name: Install latest InfluxDB
    import_tasks: influxdb-installation.yml
    tags:
      - installation
      - influxdb-installation
  - name: Install latest Grafana
    import_tasks: grafana-installation.yml
    tags:
      - installation
      - grafana-installation
  - name: Install latest Ansible
    import_tasks: ansible-installation.yml
    tags:
      - installation
      - ansible-installation
  - name: Configure monitoring
    import_tasks: monitoring-configuration.yml
    tags:
      - configuration
