---
- hosts: monitor
  become: yes
  roles:
  - codeyourinfra.grafana
  tasks:
  - name: Install required Ubuntu packages
    apt:
      name: '{{item}}'
      update_cache: yes
    loop:
      - apt-transport-https
      - python3-pip
    tags:
      - requirements-installation
  - name: Install latest InfluxDB
    import_tasks: influxdb-installation.yml
    tags:
      - influxdb-installation
  - name: Install latest Ansible
    import_tasks: ansible-installation.yml
    tags:
      - ansible-installation
