---
- hosts: monitor
  become: yes

  roles:
  - codeyourinfra.grafana
  - codeyourinfra.influxdb
  - codeyourinfra.ansible

  tasks:
  - name: Get Ubuntu version
    shell: lsb_release -ds
    register: ubuntu_version_result
  - name: Show Ubuntu version
    debug:
      msg: "{{ ubuntu_version_result.stdout_lines[0] }}"
  - name: Store Ubuntu version
    copy:
      dest: ubuntu-version.txt
      content: "{{ ubuntu_version_result.stdout_lines[0] }}"
    delegate_to: localhost

  - name: Install curl
    apt:
      name: curl
  - name: Get Grafana version
    shell: curl -s localhost:3000/login | grep span warn=no
    register: grafana_version_result
  - name: Set Grafana version fact
    set_fact:
      grafana_version: "{{ grafana_version_result.stdout_lines[0] | regex_search('(v[\\d.]+)') }}"
  - name: Show Grafana version
    debug:
      msg: "{{ grafana_version }}"
  - name: Store Grafana version
    copy:
      dest: grafana-version.txt
      content: "{{ grafana_version }}"
    delegate_to: localhost
  
  - name: Get InfluxDB version
    shell: influxd version
    register: influxdb_version_result
  - name: Set InfluxDB version fact
    set_fact:
      influxdb_version: "{{ influxdb_version_result.stdout_lines[0] | regex_search('(v[\\d.]+)') }}"
  - name: Show InfluxDB version
    debug:
      msg: "{{ influxdb_version }}"
  - name: Store InfluxDB version
    copy:
      dest: influxdb-version.txt
      content: "{{ influxdb_version }}"
    delegate_to: localhost
  
  - name: Get Ansible version
    shell: ansible --version
    register: ansible_version_result
  - name: Set Ansible version fact
    set_fact:
      monitor_ansible_version: "{{ ansible_version_result.stdout_lines[0] | regex_search('([\\d.]+)') }}"
  - name: Show Ansible version
    debug:
      msg: "{{ monitor_ansible_version }}"
  - name: Store Ansible version
    copy:
      dest: ansible-version.txt
      content: "{{ monitor_ansible_version }}"
    delegate_to: localhost

  - name: Minimize disk space
    script: ../minimize.sh
