# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "ubuntu/xenial64"
    monitor.vm.network "private_network", ip: "192.168.33.10"
    monitor.ssh.insert_key = false
    monitor.vm.provision "ansible" do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "playbook-monitor.yml"
      ansible.host_vars = {
        "monitor" => {"ansible_python_interpreter" => "/usr/bin/python3"}
      }
    end
  end
end
